cameras:
- id: cam0
  name: USB0
  source: '0'
  regions_file: config/regions.json
  profile: accurate
  device: auto
  imgsz: auto
  auto_tune: true
  active: true
  auto_start: false
- id: vid1
  name: 测试视频
  source: tests/fixtures/videos/20250724072708.mp4
  regions_file: config/regions.json
  profile: accurate
  device: auto
  imgsz: auto
  auto_tune: true
  active: true
  auto_start: false
  env:
    REDIS_HOST: 127.0.0.1
    REDIS_PORT: "6379"
    REDIS_DB: "0"
    REDIS_PASSWORD: pyt_dev_redis
    VIDEO_STREAM_USE_REDIS: "1"
