apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - pvc.yaml
  - postgres.yaml
  - redis.yaml
  - api.yaml
  - nginx.yaml
  - monitoring.yaml
  - hpa.yaml

# 在所有资源中添加命名空间
namespace: pepgmp-prod